version: '3'
services:
  react:
    container_name: react-app
    build: ./react-app
    ports: 
      - '80:80'
    links:
      - server
  server:
    container_name: node-mongo-docker
    restart: always
    build: ./node-mongo
    ports:
      - '5000:5000'
    links:
      - mongo
    # volumes:
    #   - '.:/usr/src/app'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
